Redesigned plugin

diff --git a/MongoDB-monitor/bash/standalone/monitis-mongo-plugin b/MongoDB-monitor/bash/standalone/monitis-mongo-plugin
--- a/MongoDB-monitor/bash/standalone/monitis-mongo-plugin
+++ b/MongoDB-monitor/bash/standalone/monitis-mongo-plugin
@@ -1,17 +1,53 @@
 #!/bin/bash
 :
+
 #set -x
 SED=$(which sed)
 AWK=$(which awk)
-MONGOSTAT=$(which mongostat)
 TAIL=$(which tail)
 GREP=$(which grep)
+MONGO=$(which mongo)
+PREV_FILE=.mmm_prev
+empty=0
 #
 declare OUTPUT
+declare prev
+declare current
+declare result
+declare save_value
+#
 USE_AUTH=false
 PARAM_ERROR_STRING="Missing parameter name"
 RETURN_CODE=0
+##############
+
 #
+save(){
+	echo "$1"|sed -e 's/^[ \r]*//' > $PREV_FILE
+}
+##############
+usage(){
+
+        echo "Usage: $0 [-user|--user <username> -pwd|--pwd <password>]  -host|--host <hostname> -port|--port <port> -metrics|--metrics <metric1,metric2,metricN>"
+echo "Supported metrics are: "
+echo ""
+echo "  inserts  	- # of inserts per second (* means replicated op)"
+echo "  query    	- # of queries per second"
+echo "  update   	- # of updates per second"
+echo "  delete   	- # of deletes per second"
+echo "  getmore  	- # of get mores (cursor batch) per second"
+echo "  command  	- # of commands per second, on a slave its local|replicated"
+echo "  flushes  	- # of fsync flushes per second"
+echo "  mapped   	- amount of data mmaped (total data size) megabytes"
+echo "  vsize    	- virtual size of process in megabytes"
+echo "  res      	- resident size of process in megabytes"
+echo "  faults   	- # of pages faults per sec (linux only)"
+echo "  netIn    	- network traffic in - bits"
+echo "  netOut   	- network traffic out - bits"
+
+        RETURN_CODE=1
+        exit $RETURN_CODE
+}
 ##################################################################################################
 # Checking for required tools
 ##################################################################################################
@@ -27,9 +63,9 @@ echo "awk not found"
 exit 1
 fi
 #
-if [[ -z $MONGOSTAT ]]
+if [[ -z $MONGO ]]
 then
-echo "mongostat not found"
+echo "mongo not found"
 exit 1
 fi
 #
@@ -60,11 +96,14 @@ do
     	-h | --host | -host )  			HOST="$2"; shift	;;
     	-t | --port | -port )  			PORT="$2"; shift	;;
     	-m | --metrics | -metrics )		METRICS="$2"; shift ;;
-
+	-d | --database | -database )		DB="$2"; shift ;;
     	*) ;; # unknown option		
   	esac
   	shift
 done
+#
+METRICS=${METRICS/'['/''}
+METRICS=${METRICS/%']'/''}
 #
 if [[ -n $USERNAME ]]
 then
@@ -103,76 +142,276 @@ else
 	MONGOSTAT_OPTS=" --host $HOST:$PORT"
 fi
 #
-metrics=$($MONGOSTAT $MONGOSTAT_OPTS -n 1|$TAIL -1)
-error=$(echo $metrics|$GREP 'failed')
-if [[ -n $error ]]
+if [[ ! -f $PREV_FILE || -z $(cat $PREV_FILE) ]]
 then
-	exit 1
+	empty=1
+	
 fi
+#
 #
 splited_metrics=$(echo $METRICS|tr ',' ' ')
 for metric in $splited_metrics
 do
 	case "$metric" in
 	"insert")
-	OUTPUT=" $OUTPUT insert="$(echo $metrics|$AWK '{print $1}')
+	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'insert'|$AWK '{print $2}')
+	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["opcounters"]["insert"]' $DB|$TAIL -1)
+	if [[ -z $prev ]]
+	then
+		result=0
+	else
+		result=$(( ($current-$prev) / 300))
+	fi
+	if [[ $result -lt 0 ]]
+	then
+		echo "wrongResult=true"
+		exit
+	else
+		OUTPUT=" $OUTPUT insert="$result
+	fi
+	save_value="$save_value insert "$(echo $result|sed "s/$/\\`echo -e '\n\r'`/g")
 	;;
+##########
 	"query")
-	OUTPUT=" $OUTPUT query="$(echo $metrics|$AWK '{print $2}')
+	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'query'|$AWK '{print $2}')
+	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["opcounters"]["query"]' $DB|$TAIL -1)
+	if [[ -z $prev ]]
+	then
+		result=0
+	else
+		result=$(( ($current-$prev) / 300))
+	fi
+	if [[ $result -lt 0 ]]
+	then
+		echo "wrongResult=true"
+		exit
+	else
+		OUTPUT=" $OUTPUT query="$result
+	fi
+	save_value="$save_value query "$(echo $result|sed "s/$/\\`echo -e '\n\r'`/g")
 	;;
+##########
 	"update")
-	OUTPUT=" $OUTPUT update="$(echo $metrics|$AWK '{print $3}')
+	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'update'|$AWK '{print $2}')
+	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["opcounters"]["update"]' $DB|$TAIL -1)
+	if [[ -z $prev ]]
+	then
+		result=0
+	else
+		result=$(( ($current-$prev) / 300))
+	fi
+	if [[ $result -lt 0 ]]
+	then
+		echo "wrongResult=true"
+		exit
+	else
+		OUTPUT=" $OUTPUT update="$result
+	fi
+	save_value="$save_value update "$(echo $result|sed "s/$/\\`echo -e '\n\r'`/g")
 	;;
+##########
 	"delete")
-	OUTPUT=" $OUTPUT delete="$(echo $metrics|$AWK '{print $4}')
+	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'delete'|$AWK '{print $2}')
+	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["opcounters"]["delete"]' $DB|$TAIL -1)
+	if [[ -z $prev ]]
+	then
+		result=0
+	else
+		result=$(( ($current-$prev) / 300))
+	fi
+	if [[ $result -lt 0 ]]
+	then
+		echo "wrongResult=true"
+		exit
+	else
+		OUTPUT=" $OUTPUT delete="$result
+	fi
+	save_value="$save_value delete "$(echo $result|sed "s/$/\\`echo -e '\n\r'`/g")
 	;;
+##########
 	"getmore")
-	OUTPUT=" $OUTPUT getmore="$(echo $metrics|$AWK '{print $5}')
+	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'getmore'|$AWK '{print $2}')
+	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["opcounters"]["getmore"]' $DB|$TAIL -1)
+	if [[ -z $prev ]]
+	then
+		result=0
+	else
+		result=$(( ($current-$prev) / 300))
+	fi
+	if [[ $result -lt 0 ]]
+	then
+		echo "wrongResult=true"
+		exit
+	else
+		OUTPUT=" $OUTPUT getmore="$result
+	fi
+	save_value="$save_value getmore "$(echo $result|sed "s/$/\\`echo -e '\n\r'`/g")
 	;;
+##########
 	"command")
-	OUTPUT=" $OUTPUT command="$(echo $metrics|$AWK '{print $6}')	
+	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'command'|$AWK '{print $2}')
+	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["opcounters"]["command"]' $DB|$TAIL -1)
+	if [[ -z $prev ]]
+	then
+		result=0
+	else
+		result=$(( ($current-$prev) / 300))
+	fi
+	if [[ $result -lt 0 ]]
+	then
+		echo "wrongResult=true"
+		exit
+	else
+		OUTPUT=" $OUTPUT command="$result
+	fi
+	save_value="$save_value command "$(echo $result|sed "s/$/\\`echo -e '\n\r'`/g")
 	;;
+##########
 	"flushes")
-	OUTPUT=" $OUTPUT flushes="$(echo $metrics|$AWK '{print $7}')
+	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'flushes'|$AWK '{print $2}')
+	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["backgroundFlushing"]["flushes"]' $DB|$TAIL -1)
+	if [[ -z $prev ]]
+	then
+		result=0
+	else
+		result=$(( ($current-$prev) / 300))
+	fi
+	if [[ $result -lt 0 ]]
+	then
+		echo "wrongResult=true"
+		exit
+	else
+		OUTPUT=" $OUTPUT flushes="$result
+	fi
+	save_value="$save_value flushes "$(echo $result|sed "s/$/\\`echo -e '\n\r'`/g")
 	;;
+##########
 	"mapped")
-	OUTPUT=" $OUTPUT mapped="$(echo $metrics|$AWK '{print $8}')
+	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'mapped'|$AWK '{print $2}')
+	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["mem"]["mapped"]' $DB|$TAIL -1)
+	if [[ -z $prev ]]
+	then
+		result=0
+	else
+		result=$(( ($current-$prev) / 300))
+	fi
+	if [[ $result -lt 0 ]]
+	then
+		echo "wrongResult=true"
+		exit
+	else
+		OUTPUT=" $OUTPUT mapped="$result
+	fi
+	save_value="$save_value mapped "$(echo $result|sed "s/$/\\`echo -e '\n\r'`/g")
 	;;
+##########
 	"vsize")
-	OUTPUT=" $OUTPUT vsize="$(echo $metrics|$AWK '{print $9}')
+	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'vsize'|$AWK '{print $2}')
+	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["mem"]["virtual"]' $DB|$TAIL -1)
+	if [[ -z $prev ]]
+	then
+		result=0
+	else
+		result=$(( ($current-$prev) / 300))
+	fi
+	if [[ $result -lt 0 ]]
+	then
+		echo "wrongResult=true"
+		exit
+	else
+		OUTPUT=" $OUTPUT vsize="$result
+	fi
+	save_value="$save_value vsize "$(echo $result|sed "s/$/\\`echo -e '\n\r'`/g")
 	;;
+##########
 	"res")
-	OUTPUT=" $OUTPUT res="$(echo $metrics|$AWK '{print $10}')
+	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'res'|$AWK '{print $2}')
+	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["mem"]["mapped"]' $DB|$TAIL -1)
+	if [[ -z $prev ]]
+	then
+		result=0
+	else
+		result=$(( ($current-$prev) / 300))
+	fi
+	if [[ $result -lt 0 ]]
+	then
+		echo "wrongResult=true"
+		exit
+	else
+		OUTPUT=" $OUTPUT res="$result
+	fi
+	save_value="$save_value res "$(echo $result|sed "s/$/\\`echo -e '\n\r'`/g")
 	;;
+##########
 	"faults")
-	OUTPUT=" $OUTPUT faults="$(echo $metrics|$AWK '{print $11}')
+	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'faults'|$AWK '{print $2}')
+	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["extra_info"]["page_faults"]' $DB|$TAIL -1)
+	if [[ -z $prev ]]
+	then
+		result=0
+	else
+		result=$(( ($current-$prev) / 300))
+	fi
+	if [[ $result -lt 0 ]]
+	then
+		echo "wrongResult=true"
+		exit
+	else
+		OUTPUT=" $OUTPUT faults="$result
+	fi
+	save_value="$save_value faults "$(echo $result|sed "s/$/\\`echo -e '\n\r'`/g")
 	;;
-	"locked")
-	OUTPUT=" $OUTPUT locked="$(echo $metrics|$AWK '{print $12}')
-	;;
+##########
 	"netIn")
-	OUTPUT=" $OUTPUT netIn="$(echo $metrics|$AWK '{print $16}')
+	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'netIn'|$AWK '{print $2}')
+	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["network"]["bytesIn"]' $DB|$TAIL -1)
+	if [[ -z $prev ]]
+	then
+		result=0
+	else
+		result=$(( ($current-$prev) / 300))
+	fi
+	if [[ $result -lt 0 ]]
+	then
+		echo "wrongResult=true"
+		exit
+	else
+		OUTPUT=" $OUTPUT netIn="$result
+	fi
+	save_value="$save_value netIn "$(echo $result|sed "s/$/\\`echo -e '\n\r'`/g")
 	;;
+##########
 	"netOut")
-	OUTPUT=" $OUTPUT netOut="$(echo $metrics|$AWK '{print $17}')
+	test $empty -ne 1 && prev=$(cat $PREV_FILE|grep 'netOut'|$AWK '{print $2}')
+	current=$($MONGO $MONGOSTAT_OPTS --eval 'db.serverStatus()["network"]["bytesOut"]' $DB|$TAIL -1)
+	if [[ -z $prev ]]
+	then
+		result=0
+	else
+		result=$(( ($current-$prev) / 300))
+	fi
+	if [[ $result -lt 0 ]]
+	then
+		echo "wrongResult=true"
+		exit
+	else
+		OUTPUT=" $OUTPUT netOut="$result
+	fi
+	save_value="$save_value netOut "$(echo $result|sed "s/$/\\`echo -e '\n\r'`/g")
 	;;
-	"conn")
-	OUTPUT=" $OUTPUT conn="$(echo $metrics|$AWK '{print $18}')
-	;;
-	"time")
-	OUTPUT=" $OUTPUT time="$(echo $metrics|$AWK '{print $19}')
-	;;
+##########
+
 esac
 done
 #
+save "$save_value"
 #
-echo $OUTPUT
+if [[ $empty -eq 1 ]]
+then
+	echo "wrongResult=true"
+else
+	echo $OUTPUT
+fi
+
 exit $RETURN_CODE
 
-
-usage(){
-
-	echo "Usage: $0 [-user|--user <username> -pwd|--pwd <password>]  -host|--host <hostname> -port|--port <port> -metrics|--metrics <metric1,metric2,metricN>"
-	RETURN_CODE=1
-	exit $RETURN_CODE
-}
